config/routes.rb
Misc2::Application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root :to => 'index#show' 
    resources :news
    match 'news' => 'news#index'
    match 'news/:id' => 'news#show'
    match 'contact' => 'contact#show'
    match 'about' => 'about#show'
    match 'service' => 'service#show'               
  end

  match '', to: redirect("/#{I18n.default_locale}")

    devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :content, :title, :image

  active_admin_translates :title, :content

  mount_uploader :image, ImageUploader
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale
  
private

  def set_locale
  	I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
  	{locale: I18n.locale}
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  	@news = New.all
  end

  def show
  	@new = New.find(params[:id])
  end

end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/about/show.html.haml
- content_for :scroll do
	%link{:rel => "stylesheet", :href => "/assets/dzsscroller/scroller.css"}
	%script{:src => "http://code.jquery.com/jquery-migrate-1.2.1.js"}	
	%script{:src => "/assets/dzsscroller/scroller.js"}
	%script{:src => "/assets/dzsscroller/init.js"}
.wrap
	.row
		= render 'nav/sidebar'
		.span6
			%h2 MICS Group profile
			%p Main activies
			.span5-1
				%ul
					%li 
						%span Freight forwarding (NVOCC)
					%li 
						%span Liner/commercial agency (incl husbandry services)
					%li 
						%span In-port container equipment tracing/supervision (for container lines) in Odessa/Ilyichevsk ports
					%li 
						%span In-port handling services (stuffing, warehousing, customs brokerage, lashing, pre-shipment cargo preparation and other related ops)
					%li 
						%span Heavy-lift cargo handling
					%li 
						%span Break bulk cargoes handling
					%li 
						%span Rail and truck inland haulage
					%li 
						%span Chartering				
			.span5-1
				.range
					.ico
						= image_tag("office-ico.png")		
						%a{:href => "/"} 3 offices in Ilychevsk and Odessa
					.ico
						= image_tag("people-ico.png")		
						%a{:href => "/"} Staff over 60 persons
					.ico
						= image_tag("cup-ico.png")		
						%a{:href => "/"} Our awards
				.grf
					%h3 5500 
					%p 	TEU/month in-port container equipment control for container lines (tally, supervision, executive bayplans perfomance)
				.stat
					%h3 Freight forwarding / liner agency services
					.stat-span
						%p 300
						%p TEU/month 
						%p (containers)
					.stat-span
						%p 10.000
						%p MT/month 
						%p (bulk) 
					.stat-span
						%p 300
						%p units/month 
						%p (vehicles) 
		.row.slide
			%h3 Higlights
			.row
				%div{ :id => "scrollc5", :class => "scroller-con", :style => "width: 995px; height: 155px;" }
					%div{ :class => "inner", :style => "width: 2000px" }
						.span3
							%h4 1995
							%p Company founded in june 1995 by the three shareholders (private persons)
						.span3
							%h4 1995 1997
							%p Firstirst logistic contracts with MAERSK (A.P. Moller, Denmark), SEALAND (USA), CMN Marseille (France) – container equipment tracing & survey
						.span3
							%h4 1998 2000
							%p First agency agreements with MBS Marseille (France), EMES (ARKAS Group, Turkey)
						.span3	
							%h4 2004-2008
							%p Foundation of NVOCC partnership with Global Link Logistics (China), BDP International (Indonesia), ABS Marseille (France), BDP India, Kartash inc. (USA), Roberto Bucci (Italy)
						.span3
							%h4 1995
							%p Company founded in june 1995 by the three shareholders (private persons)
						.span3
							%h4 1995 1997
							%p Firstirst logistic contracts with MAERSK (A.P. Moller, Denmark), SEALAND (USA), CMN Marseille (France) – container equipment tracing & survey
						.span3
							%h4 1998 2000
							%p First agency agreements with MBS Marseille (France), EMES (ARKAS Group, Turkey)
						.span3	
							%h4 2004-2008
							%p Foundation of NVOCC partnership with Global Link Logistics (China), BDP International (Indonesia), ABS Marseille (France), BDP India, Kartash inc. (USA), Roberto Bucci (Italy)
		.row.logos
			%h3 MICS’ customers (incl direct/indirect contracts)
			= image_tag("about-logo-1.png")
			= image_tag("about-logo-2.png")
			= image_tag("about-logo-3.png")
			= image_tag("about-logo-4.png")
			%p MFC Commodities, Container Terminal Ilyichevsk, Trade House Elvas, Trade House Promshina, Metprom Ltd, Trade House Mikko, Norma Apecs, Invest-ceramica llc, Lyudinovoteplovoz, Tulachermet, MAY Company, ISC Novokramatorsk Machine Building Works, Druzhkovka Hardware Plant, Elcor Corporation, South Trade Company, Himagro and others…

app/views/contact/show.html.haml
- content_for :scripts do
	%script{:src => "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"}	
	%script{:src => "/assets/api/api.js"}
.wrap
	.row
		= render 'nav/sidebar'
		.span6	
			%section
				.span5-6
					%h2 Контактная информация
					#map					
					%h3 Филиалы и дочерние компании:
					.h-span
						.span2-3
							%p 
								%span 
									%b Ильичевский филиал «МИКС»:
								%span 
									%i
										(Внутрипортовая обработка и экспедирование грузов) 
								%p Ильичевск 68003, Одесская обл. Бульвар Гайдара 7-Б
								%span Тел/факс:
								%p.tel	+38 04868 35 600
								%p.email
									email:
									%a{ :href => "mailto:port@mics.com.ua" } port@mics.com.ua			
						.span2-3
							%p 
								%span 
									%b ООО «МИКС-Лайн»
								%span 
									%i
										(Перевозка и обработка автомобилей и накатной техники)			
								%p Тел/факс:
								%p.tel	+38 04868 24 981
								%p.email
									email:
									%a{ :href => "mailto:roro@mics.com.ua" } roro@mics.com.ua
				.span2-3 
					.address
						%h3 ООО «МИКС»											
						%p.adr
							%span 
								%b Головной офис:
							%span Одесса 65044, 
							%span пр-т Шевченко 4-Д,
							%span БЦ «Шевченковский», Офис 82						
							%span Тел/факс:
						%p.tel						
							+38 048 77 60 333
						%p.tel	
							+38 048 77 60 444
						%p.tel
							+38 048 77 60 555
						%p.email 
							email:
							%a{ :href => "mailto:mics@mics.com.ua" } mics@mics.com.ua
							%a{ :href => "mailto:kalinovich@mics.com.ua" } kalinovich@mics.com.ua
						.h-span2-3
							%p
								%span 
									%b ООО «МИКС-Логистик»
								%span
									%i (Перевозка и обработка автомобилей и накатной техники)			
								%p Тел/факс:
								%p.tel	+38 04868 304309
								%p.email
									email:
									%a{ :href => "mailto:logis@mics.com.ua" } logis@mics.com.ua

app/views/index/_parallax.html.haml
%div#parallax					
	=image_tag("leaf-1.png", :class => "leaf-1")
	=image_tag("leaf-2.png", :class => "leaf-2")
	=image_tag("leaf-3.png", :class => "leaf-3")
	=image_tag("leaf-4.png", :class => "leaf-4")
	=image_tag("leaf-5.png", :class => "leaf-5")
	=image_tag("leaf-6.png", :class => "leaf-6")
	=image_tag("bubble-1.png", :class => "bubble-1")
	=image_tag("bubble-2.png", :class => "bubble-2")
	=image_tag("bubble-3.png", :class => "bubble-3")
	=image_tag("bubble-4.png", :class => "bubble-4")
	=image_tag("bubble-5.png", :class => "bubble-5")
	=image_tag("bubble-6.png", :class => "bubble-6")
	=image_tag("bubble-7.png", :class => "bubble-7")
	=image_tag("bubble-8.png", :class => "bubble-8")


app/views/index/show.html.haml
%div.wrap	
	%div.desc 
		%p.item-1 Современная
		%p.item-2 ДОСТАВКА ГРУЗОВ
		%p.item-3 оперативно и надежно
%div.wrap_big
	%div.top-img-1.active
		= image_tag("sld_1.jpg")
	%div.top-img-2
		= image_tag("sld_2.jpg")
	%div.top-img-3
		= image_tag("sld_3.jpg")
.wrap
	%section		
		.row.nav	
			.span2-5
				%h3 УСЛУГИ
				%p отсортированы по типам перевозок
			%div.nav-menu
				.span3.active
					%p контейнерные			
				.span3
					%p грузы Po-Po
				.span3	
					%p навалочные грузы				
	%section
		.row.news
			.span2-5
				%div.h-news-single
					%h4				
						02
						%span декабря		
					.h-redline		
						%a{ :href=> "/" } 
							%span На чемпионате Европы Украина сыграет с Англией, Францией и Швецией 02 декабря
			.span3
				%div.h-news-single
					%h4
						14
						%span мая
					.h-redline
						%a{ :href=> "/" } 
							%span В Москве, в концертном зале «Известия Холл» прошла долгожданная презентация легендарного бизнес седана Honda Accord 01 декабря
			.span3
				%div.h-news-single
					%h4
						21
						%span ноября
					.h-redline
						%a{ :href=> "/" } 
							%span УЕФА завел дисциплинарное дело на Луиса Адриану. Лига чемпионов 21 ноября
			.span3
				%div.h-news-single
					= image_tag("ico_car.png", :alt=>"Misc")
					.h-redline
						%a{ :href=> "/" } 
							%span Спец. предложения по перевозке комбайнов
		.row.news-out			
			%a{ :href=> "/", :class => "redline" } 
				%span Все новости

app/views/layouts/application.html.haml
!!!
%html(lang="en"){ :class => "no-js" }
	%head
		/[if lte IE 8]
			%script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}		
	= stylesheet_link_tag    "application", :media => "all"	
	- if current_page?(contact_path)
		= yield :scripts	
	= javascript_include_tag "application"
	- if current_page?(about_path)
		= yield :scroll
	- if current_page?(:controller => "news")
		= yield :scroll
	- if current_page?(service_path)
		= yield :fancy
	= csrf_meta_tags	
	%body{ :id => "#{params[:controller].parameterize}_controller" }
		.main
			.wrap
				- if current_page?(root_path)
					= render 'index/parallax'
				= render 'nav/header'
			= yield		
			.hFooter
		%footer.footer
			= render 'nav/footer'	

app/views/nav/_footer.html.haml
.wrap
	.row
		.span4
			= image_tag("ftr-c.png")
			%p Все права плюс свежая черника MICS Ltd, 2012
		.span4.mv-center
			%p 
				%sup +38
				022 722 546
			%div
				= image_tag("ftr-phone.png")
				%p.redline
					%span Контактная информация
		.span4.mv-center
			= image_tag("ftr-ico.png")		
			%p 
				Разработка и дизайн сайта: 
				%a{ :href=> "/", :class => "redline" }
					%span Hippocampus
				art united

app/views/nav/_header.html.haml
.row
	%header.header	
		%h1 		
			%a{:href=>"/"}
				= image_tag("logo.png", :alt=>"Misc")
		%nav.nvg
			%ul.hdr-lang.pull-right 
				%li
					%span
						=link_to_unless_current "Ru", locale: "ru"
					%span
						=link_to_unless_current "En", locale: "en"							
			%div.nav-stick.pull-right			
			%ul.hdr-menu.pull-right 
				%li{ class: (current_page?(about_path))? 'active' : nil }						
					= link_to "#{t "nav.about"}", about_path
				%li{ class: (current_page?(service_path))? 'active' : nil }					
					= link_to 'Услуги', service_path
				%li 
					= link_to 'Документация'
				%li{ class: (current_page?(:controller => "news"))? 'active' : nil }	 
					= link_to 'Новости', :controller => "news", :action => "index"
				%li 
					= link_to 'Галерея'
				%li{ class: (current_page?(contact_path))? 'active' : nil }	 
					= link_to 'Контакты', contact_path 
			= image_tag("header-triangle.png", :alt=>"Misc", :class => "hdr-menu-border")
	

app/views/nav/_sidebar.html.haml
.span2
	%h2.cat-title 
		%span НАШИ
		УСЛУГИ:
	.cat-list
		%ul
			%li				
				= image_tag("cat-list-top-ico.png", :class => "pull-right")
				%p контейнерные
		%ul
			%li				
				= image_tag("cat-list-top-ico.png", :class => "pull-right")
				%p грузы Ро-Ро
		%ul
			%li				
				= image_tag("cat-list-top-ico.png", :class => "pull-right")
				%p навалочные грузы
	-if current_page?(url_for(:controller => 'contact', :action => 'show'))		
		#map_small
	-if current_page?(:controller => 'news')			
		#datepicker		

app/views/news/index.html.haml
- content_for :scroll do
	%link{:rel => "stylesheet", :href => "/assets/dzsscroller/scroller.css"}
	%link{:rel => "stylesheet", :href => "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"}
	%link{:rel => "stylesheet", :href => "/assets/datepicker/datepicker.css"}	
	%script{:src => "http://code.jquery.com/jquery-migrate-1.2.1.js"}	
	%script{:src => "http://code.jquery.com/ui/1.10.3/jquery-ui.js"}
	%script{:src => "/assets/datepicker/jquery.ui.datepicker-ru.js"}
	%script{:src => "/assets/datepicker/init.js"}
	%script{:src => "/assets/dzsscroller/scroller.js"}
	%script{:src => "/assets/dzsscroller/init.js"}	
.wrap
	.row
		= render 'nav/sidebar'
		.span6
			.h-span6
				%h2 Новости
				%h3 
					=@news.last.title
				%div.date
					=@news.last.created_at.day
					%span						
						=I18n.l @news.last.created_at, :format => :custom
				%div.single
					=image_tag @news.last.image_url(:thumb).to_s
					%div 
						=@news.last.content.html_safe
			.news
				%h3 Все новости				
				%div{ :id => "scrollc4", :class => "scroller-con", :style => "width: 700px; height: 150px;" }
					%div{ :class => "inner", :style => "width: 1250px; height: 150px;" }		
						- @news.each do |new|	
							.span2	
								.h-span
									%div.date
										=new.created_at.day 
										%span 
											=I18n.l new.created_at, :format => :custom	
									.h-redline	
										= link_to new do
											<span>#{new.title}</span>
												
									
						

app/views/news/show.html.haml
- content_for :scroll do
	%link{:rel => "stylesheet", :href => "/assets/dzsscroller/scroller.css"}
	%link{:rel => "stylesheet", :href => "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"}
	%link{:rel => "stylesheet", :href => "/assets/datepicker/datepicker.css"}	
	%script{:src => "http://code.jquery.com/jquery-migrate-1.2.1.js"}	
	%script{:src => "http://code.jquery.com/ui/1.10.3/jquery-ui.js"}
	%script{:src => "/assets/datepicker/jquery.ui.datepicker-ru.js"}
	%script{:src => "/assets/datepicker/init.js"}
	%script{:src => "/assets/dzsscroller/scroller.js"}
	%script{:src => "/assets/dzsscroller/init.js"}	
.wrap
	.row
		= render 'nav/sidebar'
		.span6
			.h-span6
				%h2 Новости
				%h3 Киевсовет разрешил «скрытую приватизацию»
				%div.date
					14 
					%span мая
				%div.single
					%img{ :src => "assets/single-news.jpg"}
					%p Депутаты Киевсовета реорганизовали 8 кинотеатров в коммунальную собственность территориальной общины города и присоединили их к КП "Киевкинофильм". За это решение проголосовало 72 депутата.
					%p	Согласно решения Киевгорадминистрации, будет создана специальная комиссия, которая осуществит организационно-правовые мероприятия и утвердит передаточные акты. 
					%p "Например кинотеатр" Киевская Русь ", помещение которого - несколько тысяч кв.метров - находится 15 лет в аренде и платит всего 2000 долларов за нее. Кинотеатр уже доведен до полного упадка. Это позор, такого не должно быть ", - говорит с трибуны Виктор Корж, заместитель председателя КГГА.
					%p В кулуарах Виктор Корж пояснил, что директора кинотеатров заключили копеечные договоры аренды, которые не отражают стоимость уставных фондов. Из-за них горд не досчитался около 3, 5 млн грн. Убытки не оговорены неэффективностью заведения, а сознательным занижением арендной платы, убежден он.
					%p "Решениями судов некоторые директора назначали себя пожизненно на эту должность. Это же абсурд. Гражданам все равно в каком юридическом статусе находятся кинотеатры. Им важно получить доступную услугу по приемлемой цене. Мы принимаем это решение для притока инвестиций ", - отметил он.
					%p Заместитель председателя КГГА заверил, что перепрофилирование этих учреждений невозможно.
			.news
				%h3 Все новости				
				%div{ :id => "scrollc4", :class => "scroller-con", :style => "width: 700px; height: 150px;" }
					%div{ :class => "inner", :style => "width: 1250px; height: 150px;" }
						.span2
							.h-span
								%div.date
									02 
									%span декабря	
								.h-redline					
									%a{ :href=> "/" } 
										%span На чемпионате Европы Украина сыграет с Англией, Францией и Швецией 02 декабря
						.span2
							.h-span
								%div.date
									14 
									%span мая				
								.h-redline
									%a{ :href=> "/" } 
										%span В Москве, в концертном зале «Известия Холл» прошла долгожданная презентация легендарного бизнес седана Honda Accord
						.span2
							.h-span
								%div.date
									21 
									%span декабря				
								.h-redline
									%a{ :href=> "/" } 
										%span УЕФА завел дисциплинарное дело Луиса Адриану. Лига чемпионов 21 ноября
						.span2
							.h-span
								%div.date
									14 
									%span мая	
								.h-redline				
									%a{ :href=> "/" } 
										%span На чемпионате Европы Украина сыграет с Англией, Францией и Швецией 02 декабря
						.span2
							.h-span
								%div.date
									14 
									%span мая					
								.h-redline	
									%a{ :href=> "/" } 
										%span На чемпионате Европы Украина сыграет с Англией, Францией и Швецией 02 декабря
					

app/views/service/show.html.haml
- content_for :fancy do
	%script{:src => "/assets/scrollto/index.js"}	
.wrap
	.row
		.span2
			%h2.cat-title 
				%span НАШИ
				УСЛУГИ:
			%nav.cat-list				
				%ul.active.height
					%li	
						= image_tag("cat-list-ico-1.png")					
						= image_tag("cat-list-top-ico.png", :class => "pull-right")
						%p контейнерные
					%li.active 
						%a{ :href => "#content-1" } Общая информация
					%li 
						%a{ :href => "#content-2" } Фрахтовое экспедирование					
					%li 
						%a{ :href => "#content-3" } Судовое/Линейное агентирование 
					%li 
						%a{ :href => "#content-4" } Внутрипортовая перевалка 
					%li 
						%a{ :href => "#content-5" } Таможенные брокерские услуги
					%li 
						%a{ :href => "/" } Тальманские и сюрвейерские услуги, слежение за контейнерами
					%li 
						%a{ :href => "/" } Подать заявку	 
				%ul
					%li	
						= image_tag("cat-list-ico-2.png")					
						= image_tag("cat-list-top-ico.png", :class => "pull-right")
						%p грузы Ро-Ро
					%li 
						%a{ :href => "/" } Фрахтовое экспедирование					
					%li 
						%a{ :href => "/" } Судовое/Линейное агентирование 
					%li 
						%a{ :href => "/" } Внутрипортовая перевалка 
					%li 
						%a{ :href => "/" } Таможенные брокерские услуги
					%li 
						%a{ :href => "/" } Тальманские и сюрвейерские услуги, слежение за контейнерами
					%li 
						%a{ :href => "/" } Подать заявку
				%ul
					%li	
						= image_tag("cat-list-ico-3.png")					
						= image_tag("cat-list-top-ico.png", :class => "pull-right")
						%p навалочные грузы
					%li 
						%a{ :href => "/" } Фрахтовое экспедирование					
					%li 
						%a{ :href => "/" } Судовое/Линейное агентирование 
					%li 
						%a{ :href => "/" } Внутрипортовая перевалка 
					%li 
						%a{ :href => "/" } Таможенные брокерские услуги
					%li 
						%a{ :href => "/" } Тальманские и сюрвейерские услуги, слежение за контейнерами
					%li 
						%a{ :href => "/" } Подать заявку
		.span6
			.content-1
				%section
					%h2#content-1 Общая информация
					%article
						%p Благодаря многолетнему опыту работы в сфере международных перевозок, на основании наших договорных и партнерских отношений с ведущими контейнерными Линиями, логистическими и транспортными компаниями, мы можем обеспечить перевозку ваших грузов между любыми портами, а также до конечного пункта назначения. Мы выберем наилучший вариант исходя из показателей стоимости и скорости доставки. Решим вопросы, связанные с перевозкой режимных и опасных грузов. 
						%p Высокопрофессиональный состав сотрудников рассмотрит ваши заявки и ответит на них в кратчайшие сроки.	
						.aside			
							= image_tag("service-content-img-1.jpg", :class => 'pull-left')
							= image_tag("service-content-img-2.jpg")
							%p.sign Доверьте решение своих транспортных задач специалистам
							.ico
								= image_tag("info-ico.png")		
								%a{:href => "/"} Полезная информация
			.content-2
				%section
					%h2#content-2 Фрахтовое экспедирование
					%article
						.span5
							%p Для вас будет выбран и предложен оптимальный вариант доставки контейнерных грузов, решены вопросы выделения и подачи контейнерного оборудования под загрузку. 						
							%p Мы поможем провести все необходимые платежи при расчетах с линией – агентские, погрузка, фрахт и др., согласуем с выбранной Линией размещение букировки на конкретное судно. По итогам отгрузки оформим выпуск коносаментов, а также будем информировать вас о всех этапах перевозки и доставки.	
							%p.sign Просто скажите что и куда вам нужно доставить
							= image_tag("service-content-2-img-1.jpg", :class => 'pull-left')
						.span4-5														
							= image_tag("service-content-2-img-2.jpg")
							.ico
								= image_tag("info-ico.png")		
								%a{:href => "/"} Полезная информация
							.ico
								= image_tag("stat-ico.png")		
								%a{:href => "/"} Любопытная статистика		
			.content-3
				%section
					%h2#content-3 Внутрипортовая перевалка
					%article						
						%p Производим полный комплекс внутрипортовых услуг, включающий в себя накопление грузовых партий, складирование, предотгрузочную подготовку, ремонт и доработку грузовых мест, инспектирование, собственно грузовые операции, включая все возможные варианты приема и перевалки грузов – с/на автотранспорт и ж/д, затарку/растарку контейнеров, оформление комплекта товаросопроводительных документов и прочие специфические услуги. Проведем расчет требуемого количества контейнеров для перевозки ваших грузов, а также, при необходимости, обеспечим крепление и сепарацию груза в контейнере.
						.aside							
							= image_tag("service-content-3-img-1.png")
							.ico
								= image_tag("fuckt-ico.png")		
								%a{:href => "/"} Интересные факты
							%p.sign Ваш груз будет отгружен из порта в лучшем виде
			.content-4
				%section
					%h2#content-4 Таможенные брокерские услуги
					%article						
						%p Помимо стандартных таможенных формальностей, связанных с прохождением грузов через порты, предоставляем различные виды брокерских услуг – таможенная очистка грузов, следующих в импорте, экспорте и транзите, выпуск и оформление таможенных деклараций, обеспечение финансовых гарантий.
						.aside							
							= image_tag("service-content-4-img-1.jpg")
							.pull-left
								.ico
									= image_tag("info-ico.png")		
									%a{:href => "/"} Полезная информация
								.ico
									= image_tag("stat-ico.png")		
									%a{:href => "/"} Любобытная статистика
								.ico
									= image_tag("fuckt-ico.png")		
									%a{:href => "/"} Интересные факты
							%p.sign Правильное таможенное оформление груза – залог вашей безопасности
			.content-5
				%section
					%h2#content-5 Тальманские и сюрвейерские услуги, слежение за контейнерами
					%article
						.aside 
							.span5	
								%p Специфический вид услуг, являющийся визитной карточкой нашей компании с момента её основания – организация контроля за движением контейнерного оборудования в портах, представляющего непосредственный интерес для контейнерных Линий. В комплекс услуг входят тальманство, дефектация, инспектирование, организация учета и отчетности по движению контейнеров в электронном варианте, а также составление бей-планов и контроль выдачи контейнерного оборудования третьим сторонам.
								= image_tag("service-content-5-img-1.jpg")					
						.aside	
							= image_tag("service-content-5-img-2.jpg")
							%p.sign Вы будете знать в любой момент времени где находится наш контейнер
							.pull-left
								.ico
									= image_tag("info-ico.png")		
									%a{:href => "/"} Полезная информация
								.ico
									= image_tag("stat-ico.png")		
									%a{:href => "/"} Любобытная статистика
								.ico
									= image_tag("history-ico.png")		
									%a{:href => "/"} Истерическая справка